### PR TITLE
added static ads

### PR DESCRIPTION
**Pull request by DariusIurca**

### CODE REVIEW

**Comment by mapx-** [comment]
better filters

```
||sighet247.ro/banners/
sighet247.ro##.ad
```

the second one to hide the placeholders here for example:

`https://sighet247.ro/s/l-ati-vazut-politistii-maramureseni-cauta-un-barbat-de-54-de-ani-din-cicarlau-61d5a66b5c1f2/`

**Comment by S0dV** [comment]
@elaur Are you a maintainer of this repository?

**Comment by iam-py-test** [comment]
@tcptomato seems to be

**Comment by tcptomato** [comment]
I've added the filters from @mapx- because they're a little more general. Thanks for the PR

**Pull request closed without merging**
